import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('request monitor renderer', () => {
  it('uses a dedicated mini surface with four summary metrics and bounded live rows', () => {
    const source = readFileSync(new URL('../../src/renderer/src/request-monitor-window.tsx', import.meta.url), 'utf8')
    const main = readFileSync(new URL('../../src/renderer/src/main.tsx', import.meta.url), 'utf8')
    const styles = readFileSync(new URL('../../src/renderer/src/request-monitor-window.css', import.meta.url), 'utf8')
    const theme = readFileSync(new URL('../../src/renderer/src/theme.tsx', import.meta.url), 'utf8')

    expect(main).toContain("surface') === 'request-monitor'")
    expect(main).toContain('<RequestMonitorWindow />')
    expect(main).toContain('isElectron && !isRequestMonitor')
    expect(source).toContain("t('活跃', 'Active')")
    expect(source).toContain("t('首包', 'First Byte')")
    expect(source).toContain("t('耗时', 'Time')")
    expect(source).toContain('<span>Token</span>')
    expect(source).toContain('snapshot.observability.tokenCosts.allTime.totalTokens')
    expect(source).toContain('formatTokenBillions(')
    expect(source).toContain('api.getRequestMonitorAlwaysOnTop()')
    expect(source).toContain('api.toggleRequestMonitorAlwaysOnTop()')
    expect(source).toContain('api.setRequestMonitorDragging(true)')
    expect(source).toContain('api.setRequestMonitorDragging(false)')
    expect(source).toContain('onPointerDown={startDragging}')
    expect(source).toContain('className={`request-monitor__pin')
    expect(source).toContain('aria-pressed={alwaysOnTop}')
    expect(source).not.toContain('request-monitor__header')
    expect(source).not.toContain('setPreference')
    expect(source).toContain('logs.slice(0, visibleRequestLimit)')
    expect(source).toContain('applyRuntimeDelta(current, delta)')
    expect(styles).toContain('grid-template-columns: repeat(4, minmax(0, 1fr)) 18px')
    expect(styles).toContain('grid-template-columns: 8px 40px 39px minmax(28px, 1fr) auto auto')
    expect(styles).not.toMatch(/-webkit-app-region:\s*drag/)
    expect(theme).toContain("window.addEventListener('storage', syncStoredTheme)")
    expect(styles).toContain('.request-monitor__list')
    expect(styles).toContain('overflow: hidden')
    expect(styles).not.toContain('overflow: auto')
    expect(styles).toContain('@keyframes request-monitor-live-dot')
    expect(styles).toContain('.request-monitor-row--streaming > i')
    expect(styles).toContain('.request-monitor-row--success > i')
    expect(styles).toContain('-webkit-app-region: no-drag')
  })
})
