type Translate = (chinese: string, english: string) => string

/** Localizes names generated by StonePlus itself without changing user-provided names. */
export function setupPoolDisplayName(name: string, t: Translate): string {
  if (name === '向导·OAuth 智能均衡') return t(name, 'Setup · OAuth Smart Balance')
  if (name.startsWith('向导·')) return t(name, `Setup · ${name.slice('向导·'.length)}`)
  return name
}

export function conversationDisplayName(name: string | undefined, t: Translate): string | undefined {
  if (!name) return name
  const generated = name.match(/^对话 ([A-Za-z0-9._:-]+(?:…[A-Za-z0-9._:-]+)?)$/u)
  return generated ? t(name, `Conversation ${generated[1]}`) : name
}

export function accountDisplayName(name: string, t: Translate): string {
  return name === '等待选择' ? t(name, 'Pending selection') : name
}
